Спринт 10
IgorPropp/java-filmorate pull request #5
Opened 2023-12-24 11:57 UTC by IgorPropp

2023-12-25 20:22 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<@Positive Integer> likes = new HashSet<>();
Просто `Set<Integer>` тут аннотации не принято ставить.

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage filmStorage;
Нет модификаторов доступа.

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Integer> pastLikes = new HashSet<>(filmStorage.getFilms(Optional.of(id)).get(0).getLikes());
`filmStorage.getFilms` ты вызываешь три раза... зачем?
Ведь когда ты перейдешь на базу данных это будут три запроса в БД.

Не правильно пользоваться методом чтобы брать все фильмы и потом брать нулевой элемент.
Должен быть метод `getById` - который будет возвращать сущность по `id`.

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> topFilms = filmStorage.getFilms(Optional.empty()).stream()
Тут тоже не верен подход. Брать все фильмы из хранилища, а затем их сортировать...
Надо чтобы именно хранилище отдавало тебе нужное кол-во записей. 
Сейчас это просто реорганизация кода и ты можешь подумать что это не важно, но это не так...
С переходом на базу данных искать топ 10 ты будешь именно в хранилище SQL запросом.

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ValidationTest.java
> +    InMemoryFilmStorage filmStorage = new InMemoryFilmStorage();
Тесты тоже пора переместить в папку с тестами.
Она у тебя создана.

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Вот ему не хватает метода `findById()`
И вот именно этот метод должен возвращать `Optional<Film>` а не просто Film. 
Поскольку мы не знаем есть объект в хранилище или нет.

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        validateUser(user);
Хранилище не должно заниматься валидацией данных.
Эту логику нужно вынести в сервис.

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            throw new ValidationException("Пользователя с данным id не существует");
Все подобные проверки - все это нужно делать на уровне сервиса.
Хранилище этим не должно заниматься.

2023-12-25 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private boolean allUserFieldsAreValid(User user) {
А вот эти проверки, должны были быть выполнены еще на уровне контроллера - это же проверка входных параметров.

2023-12-28 05:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Обычно я студентов прошу добавлять логирование в этот контроллер и логировать ошибки на уровень log.error или log.debug. Это современный подход к траблшутингу - логировать ошибки

2023-12-28 05:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Можно лучше: Можно заменить на анотацию ломбок @RequiredArgsConstructor

2023-12-28 05:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films/{id}")
"/films/ эту часть пути лучше вынести в аннотацию на верх класса @RequestMapping

2023-12-28 05:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserService userService) {
@RequiredArgsConstructor

2023-12-28 05:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @GetMapping("/users/{id}")
/users/ в @RequestMapping

2023-12-28 05:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @NotNull
int примитив не может быть null априори. Бесполезно здесь эту аннотацию ставить или менять на класс обертку Integer. еще бы я посоветовал бы рассмотреть анноатцию для валидации строковых значний @NotBlank, могут же быть не null, но может быть передана пустая строка ""

2023-12-28 05:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
в сервисах необходимо добавить логирование и логировать все операции с сущностями(создание, обновление и т.д) это касается всех сервисов в проекте

2024-01-15 16:38 UTC, merged